version: "3.6"
services:
  wordpress:
    image: wordpress:6.5.2
    # build: .
    container_name: wordpress
    volumes:
     - ./:/var/www/html/:delegated
    #  - ./wp-content/mu-plugins:/var/www/html/wp-content/mu-plugins:delegated
      # - type: bind
      #   source: .
      #   target: /var/www/html
      #   consistency: cached
    environment:
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_TABLE_PREFIX=wp_
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=root
      - WORDPRESS_DB_PASSWORD=password
      - WP_ENVIRONMENT_TYPE=local
    depends_on:
      - db
      - phpmyadmin
      - redis # Adding Redis as a dependency for WordPress
    restart: always
    ports:
      - 80:80

  db:
    image: mariadb:latest
    container_name: db
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=wordpress
    restart: always
    ports:
      - 3306:3306

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    ports:
      - 8180:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
      UPLOAD_LIMIT: 300M

  redis: # Redis service definition
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - 6380:6379

volumes:
  db_data:
