<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit629253e74b4a3fc9c1cea8ce2e82a1f8
{
    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'PHPMailer\\PHPMailer\\' => 20,
        ),
        'A' => 
        array (
            'Acme\\' => 5,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'PHPMailer\\PHPMailer\\' => 
        array (
            0 => __DIR__ . '/..' . '/phpmailer/phpmailer/src',
        ),
        'Acme\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit629253e74b4a3fc9c1cea8ce2e82a1f8::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit629253e74b4a3fc9c1cea8ce2e82a1f8::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
