FROM wordpress:6-php8.2-apache

# Install wp-cli
RUN apt-get update && apt-get install -y less mariadb-client \
    && curl -o /usr/local/bin/wp https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar \
    && chmod +x /usr/local/bin/wp \
    && apt-get clean && rm -rf /var/lib/apt/lists/*
