<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit4f53c5e4cb875db8e7880f2a40fff2cc
{
    public static $prefixLengthsPsr4 = array (
        'S' => 
        array (
            'Stripe\\' => 7,
        ),
        'A' => 
        array (
            'Acme\\' => 5,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Stripe\\' => 
        array (
            0 => __DIR__ . '/..' . '/stripe/stripe-php/lib',
        ),
        'Acme\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit4f53c5e4cb875db8e7880f2a40fff2cc::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit4f53c5e4cb875db8e7880f2a40fff2cc::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
